--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONFEDERACIONES
--------------------------------------------------------

  CREATE TABLE "A1206898"."CONFEDERACIONES" 
   (	"CONFEDERACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into A1206898.CONFEDERACIONES
SET DEFINE OFF;
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('UEFA');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('CONCACAF');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('CONMEBOL');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('CAF');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('OFC');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('AFC');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('UEFA');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('CONCACAF');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('CONMEBOL');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('CAF');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('OFC');
Insert into A1206898.CONFEDERACIONES (CONFEDERACION) values ('AFC');
--------------------------------------------------------
--  Constraints for Table CONFEDERACIONES
--------------------------------------------------------

  ALTER TABLE "A1206898"."CONFEDERACIONES" MODIFY ("CONFEDERACION" NOT NULL ENABLE);
