
--- cracion de indices ---
CREATE BITMAP INDEX I1_D_TIEMPO ON D_TIEMPO (TEMPORADA ASC);
CREATE BITMAP INDEX I2_D_TIEMPO ON D_TIEMPO (MES ASC);

CREATE BITMAP INDEX I1_PARTIDOS ON D_PARTIDOS_CONF (CONFEDERATION);
CREATE BITMAP INDEX I2_D_PARTIDOS ON D_PARTIDOS_CONF (FECHA DESC);
CREATE BITMAP INDEX I3_D_PARTIDOS ON D_PARTIDOS_CONF (HOMETEAM);
CREATE BITMAP INDEX I4_D_PARTIDOS ON D_PARTIDOS_CONF (AWAYTEAM);




CREATE UNIQUE INDEX I1_CONF ON D_LIST_CONF (CONFEDERATION ASC);


CREATE UNIQUE INDEX I_TEMP ON D_LIST_SEASON (SEASON ASC);


CREATE BITMAP INDEX I1_H_CONF ON H_CONF (SUMA);
CREATE BITMAP INDEX I2_H_CONF ON H_CONF (DCONFEPK DESC);
CREATE BITMAP INDEX I1_H_SEASON ON H_SEASON (SUMA);
CREATE BITMAP INDEX I2_H_SEASON ON H_SEASON (DIFEREnCIA);

----- VALIDATE



  SELECT *
  FROM dba_indexes where TABLE_OWNER='FIFA' and table_name='H_CONF'
  UNION
  SELECT *
  FROM dba_indexes where TABLE_OWNER='FIFA' and table_name='H_SEASON'
 UNION
  SELECT *
  FROM dba_indexes where TABLE_OWNER='FIFA' and table_name='D_LIST_CONF'
 UNION
  SELECT *
  FROM dba_indexes where TABLE_OWNER='FIFA' and table_name='D_LIST_SEASON'
 UNION
  SELECT *
  FROM dba_indexes where TABLE_OWNER='FIFA' and table_name='D_PARTIDOS_CONF'
 UNION
  SELECT *
  FROM dba_indexes where TABLE_OWNER='FIFA' and table_name='D_TIEMPO';


