create table d_partidos as
(SELECT  'OFC' As CONFEDERATION, LEAGUE, SEASON, FECHA, HOMETEAM, AWAYTEAM, HOMESCORE, AWAYSCORE, HOMESCORE+AWAYSCORE AS GOLESPARTIDO FROM OFC@DAVIDDBQRO

UNION

SELECT 'CAF' As CONFEDERATION, LEAGUE, SEASON, FECHA, HOMETEAM, AWAYTEAM, HOMESCORE, AWAYSCORE, HOMESCORE+AWAYSCORE AS GOLESPARTIDO  FROM CAF@RAMONQRO

UNION

SELECT 'CONMEBOL' As CONFEDERATION, LEAGUE, SEASON, FECHA, HOMETEAM, AWAYTEAM, HOMESCORE, AWAYSCORE, HOMESCORE+AWAYSCORE AS GOLESPARTIDO  FROM CONMEBOL@SALMONDB 

UNION

SELECT 'CONCACAF' As CONFEDERATION, LEAGUE, SEASON, FECHA, HOMETEAM, AWAYTEAM, HOMESCORE, AWAYSCORE, HOMESCORE+AWAYSCORE AS GOLESPARTIDO  FROM CONCACAF@MANEQRO 

UNION

SELECT 'AFC' As CONFEDERATION, LEAGUE, SEASON, FECHA, HOMETEAM, AWAYTEAM, HOMESCORE, AWAYSCORE, HOMESCORE+AWAYSCORE AS GOLESPARTIDO  FROM AFC@DAVIDSLPDB

UNION

SELECT 'UEFA' As CONFEDERATION, LEAGUE, SEASON, FECHA, HOMETEAM, AWAYTEAM, HOMESCORE, AWAYSCORE, HOMESCORE+AWAYSCORE AS GOLESPARTIDO  FROM UEFA@RAMONSLP
) 
